const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=('<script>'+fs.readFileSync(require('path').join(__dirname,'../timer.js'),'utf8')+'</script>');let stored={tutorial:true,stickers:3};
function boot(){let now=100000,tick,createdPopup;const ids=new Map();function node(){return {value:'',textContent:'',innerHTML:'',open:false,closed:false,style:{setProperty(){}},classList:{toggle(){}},attrs:{},listeners:{},setAttribute(k,v){this.attrs[k]=v},addEventListener(k,f){this.listeners[k]=f},showModal(){this.open=true},close(){this.open=false},append(){},remove(){this.removed=true},querySelector(s){this.children??=new Map();if(!this.children.has(s))this.children.set(s,node());return this.children.get(s)}}}const el=id=>{if(!ids.has(id))ids.set(id,node());return ids.get(id)};const doc={getElementById:el,documentElement:node(),body:node(),head:node(),createElement:node,addEventListener(){},querySelector:node};el('mission').value='Read';
doc.baseURI="https://focus.getadhd.care/";const sandbox={URL,document:doc,console,Math,JSON,Date:{now:()=>now},setInterval:f=>tick=f,setTimeout:()=>1,clearTimeout(){},localStorage:{getItem:()=>JSON.stringify(stored),setItem:(k,v)=>stored=JSON.parse(v)},window:{addEventListener(){},open(){const events={},popupDoc={...doc,documentElement:node(),body:node(),head:node(),listeners:{},addEventListener(k,f){this.listeners[k]=f}};createdPopup={document:popupDoc,closed:false,addEventListener(k,f){events[k]=f},close(){this.closed=true;events.pagehide?.()}};return createdPopup}}};
let code=html.match(/<script>([\s\S]*?)<\/script>/)[1].replace('})();','globalThis.test={prefs,state:()=>state,start,reset,complete,attentionCheck,answerAttention,makeFloat,popout,closeMini,settings,mini:()=>float,save};})();');vm.createContext(sandbox);vm.runInContext(code,sandbox);return {t:sandbox.test,el,sandbox,popup:()=>createdPopup,advance(s){now+=s*1000;tick()}}}
(async()=>{const x=boot(),{t,el}=x;assert.equal(t.prefs.xp,30,'existing stickers receive XP');t.start();t.makeFloat();x.advance(300);assert.equal(t.state().attention,true);assert.equal(el('attention').open,false,'main modal must not make floating panel inert');assert.match(t.mini().querySelector('.mini-content').innerHTML,/data-action="attention-yes"/);assert.match(t.mini().querySelector('.mini-content').innerHTML,/data-action="attention-no"/);t.closeMini();assert.equal(el('attention').open,true,'closing compact restores unanswered check');t.answerAttention(false);assert.equal(t.state().running,false);
t.reset();t.start();await t.popout();const pop=x.popup();assert.equal(pop.closed,false,'pop-out stays open');assert.equal(typeof pop.document.listeners.click,'function','pop-out buttons are wired');x.advance(300);assert.match(pop.document.body.innerHTML,/Are you working on your mission/);assert.equal(el('attention').open,false);pop.document.listeners.click({target:{closest:()=>({dataset:{action:'attention-yes'}})}});assert.equal(t.state().running,true);assert.equal(t.state().attention,false);assert.doesNotMatch(pop.document.body.innerHTML,/attention-yes/);t.complete();assert.equal(t.prefs.xp,40);t.complete();assert.equal(t.prefs.xp,40,'duplicate completion does not award XP');assert.equal(stored.xp,40);
t.settings();for(const [id,v] of [['focus-min',7],['short-min',2],['long-min',4],['round-count',3],['volume',15]])el(id).value=v;el('checkins').checked=false;el('settings-form').onsubmit({preventDefault(){}});assert.equal(t.state().phase,'ready');assert.equal(t.state().left,420);assert.equal(t.state().running,false);assert.equal(t.state().config,null);assert.equal(el('attention').open,false);assert.equal(t.prefs.xp,40);assert.equal(t.prefs.stickers,4);assert.match(pop.document.body.innerHTML,/07:00/);t.start();assert.equal(t.state().config.focus,7);assert.equal(t.state().config.short,2);assert.equal(t.state().config.long,4);assert.equal(t.state().config.rounds,3);assert.equal(t.state().config.checkins,false);const reloaded=boot();assert.equal(reloaded.t.prefs.xp,40);assert.equal(reloaded.t.prefs.focus,7);x.sandbox.localStorage.setItem=()=>{throw Error('unavailable')};assert.equal(t.save(),false);assert.match(el('xp-storage').textContent,/unavailable/);
console.log('PASS: floating check-in is clickable without blocking modal; pop-out opens and handles Yes; closing compact restores check; save resets and applies all settings in both views; XP migration, single award, reset retention, reload persistence and storage failure.');})().catch(e=>{console.error(e);process.exitCode=1});
