const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=('<script>'+fs.readFileSync(require('path').join(__dirname,'../timer.js'),'utf8')+'</script>');let stored={tutorial:true,stickers:3};
function boot(){let now=100000,tick,createdPopup;const ids=new Map();function node(){return {play(){return Promise.resolve()},pause(){},value:'',textContent:'',innerHTML:'',open:false,closed:false,style:{setProperty(){}},classList:{toggle(){}},attrs:{},listeners:{},setAttribute(k,v){this.attrs[k]=v},addEventListener(k,f){this.listeners[k]=f},showModal(){this.open=true},close(){this.open=false},append(){},remove(){this.removed=true},querySelector(s){this.children??=new Map();if(!this.children.has(s))this.children.set(s,node());return this.children.get(s)}}}const el=id=>{if(!ids.has(id))ids.set(id,node());return ids.get(id)};const doc={getElementById:el,documentElement:node(),body:node(),head:node(),createElement:node,addEventListener(){},querySelector:node};el('mission').value='Read';
doc.baseURI="https://focus.getadhd.care/";const sandbox={URL,document:doc,console,Math,JSON,Date:{now:()=>now},setInterval:f=>tick=f,setTimeout:()=>1,clearTimeout(){},localStorage:{getItem:()=>JSON.stringify(stored),setItem:(k,v)=>stored=JSON.parse(v)},window:{addEventListener(){},open(){const events={},popupDoc={...doc,documentElement:node(),body:node(),head:node(),listeners:{},addEventListener(k,f){this.listeners[k]=f}};createdPopup={document:popupDoc,closed:false,addEventListener(k,f){events[k]=f},close(){this.closed=true;events.pagehide?.()}};return createdPopup}}};
let code=html.match(/<script>([\s\S]*?)<\/script>/)[1].replace('})();','globalThis.test={prefs,state:()=>state,start,reset,complete,attentionCheck,answerAttention,robotPose,run,openGate,gateAnswer:()=>gateAnswer,showGraphs,stickerShelf,robotLevel,robotHTML,xpBarHTML,handleClick,rollMonsters,choices:()=>monsterChoices,makeFloat,popout,closeMini,settings,mini:()=>float,save};})();');vm.createContext(sandbox);vm.runInContext(code,sandbox);return {t:sandbox.test,el,sandbox,popup:()=>createdPopup,advance(s){now+=s*1000;tick()}}}

stored={tutorial:true,xp:0};const x=boot(),t=x.t;t.start();assert.equal(t.robotPose().kind,'idle');x.advance(240);assert.equal(t.robotPose().kind,'run');x.advance(60);t.answerAttention(false);assert.equal(t.robotPose().kind,'died');x.advance(2);assert.equal(t.robotPose().frame,11);assert.equal(t.state().running,false);t.run();assert.equal(t.robotPose().kind,'run');t.attentionCheck();t.answerAttention(true);assert.equal(t.robotPose().kind,'jump');x.advance(2);assert.equal(t.robotPose().kind,'run');t.prefs.motion=true;assert.deepEqual(JSON.parse(JSON.stringify(t.robotPose())),{kind:'idle',frame:1});console.log('PASS: robot idle, locomotion, fall hold, resume, jump recovery and reduced motion');

for(const color of ['blue','green','yellow','brown']){t.handleClick({target:{closest:()=>({dataset:{colorbot:color}})}});assert.equal(t.prefs.colorRobot,color);assert.match(t.robotHTML(),new RegExp('color-robots/'+color+'/'));assert.equal(boot().t.prefs.colorRobot,color)}console.log('PASS: colorful robot selection and persistence');
