const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=('<script>'+fs.readFileSync(require('path').join(__dirname,'../timer.js'),'utf8')+'</script>');let stored={tutorial:true,stickers:3};
function boot(){let now=100000,tick,createdPopup;const ids=new Map();function node(){return {play(){return Promise.resolve()},pause(){},value:'',textContent:'',innerHTML:'',open:false,closed:false,style:{setProperty(){}},classList:{values:{},toggle(k,v){this.values[k]=v}},attrs:{},listeners:{},setAttribute(k,v){this.attrs[k]=v},addEventListener(k,f){this.listeners[k]=f},showModal(){this.open=true},close(){this.open=false},append(){},remove(){this.removed=true},querySelector(s){this.children??=new Map();if(!this.children.has(s))this.children.set(s,node());return this.children.get(s)}}}const el=id=>{if(!ids.has(id))ids.set(id,node());return ids.get(id)};const doc={getElementById:el,documentElement:node(),body:node(),head:node(),createElement:node,addEventListener(){},querySelector:node};el('mission').value='Read';
doc.baseURI="https://focus.getadhd.care/";const sandbox={URL,document:doc,console,Math,JSON,Date:{now:()=>now},setInterval:f=>tick=f,setTimeout:()=>1,clearTimeout(){},localStorage:{getItem:()=>JSON.stringify(stored),setItem:(k,v)=>stored=JSON.parse(v)},window:{addEventListener(){},open(){const events={},popupDoc={...doc,documentElement:node(),body:node(),head:node(),listeners:{},addEventListener(k,f){this.listeners[k]=f}};createdPopup={document:popupDoc,closed:false,addEventListener(k,f){events[k]=f},close(){this.closed=true;events.pagehide?.()}};return createdPopup}}};
let code=html.match(/<script>([\s\S]*?)<\/script>/)[1].replace('})();','globalThis.test={prefs,state:()=>state,start,reset,complete,attentionCheck,answerAttention,playTaskComplete,beginBreak,robotPose,robotImage,colorChoices,randomCharacterChoices,run,openGate,gateAnswer:()=>gateAnswer,showGraphs,stickerShelf,robotLevel,robotHTML,xpBarHTML,handleClick,rollMonsters,choices:()=>monsterChoices,makeFloat,popout,closeMini,settings,mini:()=>float,save};})();');vm.createContext(sandbox);vm.runInContext(code,sandbox);return {t:sandbox.test,el,sandbox,popup:()=>createdPopup,advance(s){now+=s*1000;tick()}}}

stored={tutorial:true,xp:0};const x=boot(),t=x.t;t.start();assert.equal(t.robotPose().kind,'idle');x.advance(240);assert.equal(t.robotPose().kind,'run');x.advance(60);t.answerAttention(false);assert.equal(t.robotPose().kind,'died');x.advance(2);assert.equal(t.robotPose().kind,'run');assert.equal(t.state().running,true);t.run();assert.equal(t.robotPose().kind,'run');t.attentionCheck();t.answerAttention(true);assert.equal(t.robotPose().kind,'jump');x.advance(2);assert.equal(t.robotPose().kind,'run');t.prefs.motion=true;assert.deepEqual(JSON.parse(JSON.stringify(t.robotPose())),{kind:'idle',frame:1});console.log('PASS: robot idle, locomotion, fall hold, resume, jump recovery and reduced motion');

for(const color of ['blue','green','yellow','brown']){t.handleClick({target:{closest:()=>({dataset:{colorbot:color}})}});assert.equal(t.prefs.colorRobot,color);assert.match(t.robotHTML(),new RegExp('color-robots/'+color+'/'));assert.equal(boot().t.prefs.colorRobot,color)}console.log('PASS: colorful robot selection and persistence');

const options=t.colorChoices();assert.equal((options.match(/data-colorbot=/g)||[]).length,3);assert.equal(new Set([...options.matchAll(/data-colorbot="([^"]*)"/g)].map(m=>m[1])).size,3);t.reset();assert.equal(t.colorChoices(),options,'choices stay fixed during a visit');
const originalRandom=x.sandbox.Math.random;try{x.sandbox.Math.random=()=>0;const a=t.randomCharacterChoices().join(',');x.sandbox.Math.random=()=>.999;assert.notEqual(t.randomCharacterChoices().join(','),a)}finally{x.sandbox.Math.random=originalRandom}
t.handleClick({target:{closest:()=>({dataset:{colorbot:'cute'}})}});assert.equal(boot().t.prefs.colorRobot,'cute');assert.match(t.robotHTML(),/cute-robot/);t.prefs.motion=false;t.reset();t.start();assert.match(t.robotImage(t.robotPose()),/cute-robot\/idle\//);x.advance(240);assert.match(t.robotImage(t.robotPose()),/cute-robot\/walk\//);t.prefs.checkins=false;x.advance(250);assert.match(t.robotImage({kind:'run',frame:1}),/cute-robot\/run\//);assert.match(t.robotImage({kind:'jump',frame:24}),/jump\/21.png/);assert.match(t.robotImage({kind:'died',frame:11}),/idle\/1.png/);console.log('PASS: three stable random choices, Cute Robot persistence and animation assets');

stored={tutorial:true,xp:260,activeRecruit:8,teamRoster:JSON.stringify({0:'Old adventurer',8:'Sparky'})};const robots=boot();assert.equal(robots.t.prefs.activeRecruit,8);assert.match(robots.el('team-list').innerHTML,/Sparky/);assert.doesNotMatch(robots.el('team-list').innerHTML,/Adventurer|Old adventurer|team-sprite/);assert.equal((robots.el('team-list').innerHTML.match(/class="team-member"/g)||[]).length,9);assert.equal((robots.el('team-list').innerHTML.match(/class="lab-droid"/g)||[]).length,3);robots.t.handleClick({target:{closest:()=>({dataset:{recruit:'14'}})}});robots.el('recruit-name').value='Orbit';robots.el('recruit-form').onsubmit({preventDefault(){}});assert.equal(JSON.parse(robots.t.prefs.teamRoster)[0],'Old adventurer');assert.equal(JSON.parse(robots.t.prefs.teamRoster)[8],'Sparky');assert.equal(boot().t.prefs.activeRecruit,14);assert.match(boot().t.robotHTML(),/lab-droid/);assert.equal(robots.t.prefs.xp,260);console.log('PASS: nine robot sidekicks, three lab droids, saved names and XP preserved');

stored={tutorial:true};const missions=boot();missions.t.start();missions.t.attentionCheck();missions.t.answerAttention(true);missions.t.answerAttention(true);missions.t.attentionCheck();missions.t.answerAttention(false);missions.t.run();missions.t.attentionCheck();missions.t.answerAttention(true);missions.t.showGraphs();assert.match(missions.el('graphs-content').innerHTML,/Yes 67% \(2\) · No 33% \(1\)/);assert.equal(JSON.parse(missions.t.prefs.missionHistory).length,1);const restored=boot();restored.t.showGraphs();assert.match(restored.el('graphs-content').innerHTML,/Yes 67%/);missions.t.reset();missions.t.start();missions.t.showGraphs();assert.match(missions.el('graphs-content').innerHTML,/No answered checks yet/);assert.equal(JSON.parse(missions.t.prefs.missionHistory).length,2);console.log('PASS: per-mission percentages, duplicate-answer guard, reload persistence and separate missions');

const sounds=boot();sounds.t.prefs.muted=false;sounds.t.start();const audio=sounds.el('task-complete-sound');assert.match(audio.src,/work_start.mp3$/);sounds.t.attentionCheck();sounds.t.answerAttention(false);assert.match(audio.src,/no.mp3$/);assert.equal(sounds.t.state().running,true);sounds.t.attentionCheck();sounds.t.answerAttention(true);assert.match(audio.src,/yes.mp3$/);sounds.t.beginBreak();assert.match(audio.src,/break_start.mp3$/);for(let i=0;i<6;i++){assert.equal(sounds.t.playTaskComplete(),i%5);assert.match(audio.src,new RegExp('task_'+(i%5+1)+'.mp3$'))}sounds.t.prefs.muted=true;const before=audio.src;sounds.t.playTaskComplete();assert.equal(audio.src,before);console.log('PASS: event sounds, five task variants, mute, and No resumes timer');

stored={tutorial:true};const reminder=boot();reminder.t.start();reminder.t.attentionCheck();const reminderAudio=reminder.el('task-complete-sound');reminder.advance(2.9);assert.equal(reminder.sandbox.document.body.classList.values['attention-pulse'],false);reminder.advance(.1);assert.equal(reminder.sandbox.document.body.classList.values['attention-pulse'],true);assert.doesNotMatch(reminderAudio.src,/hello_/);reminder.advance(5);assert.match(reminderAudio.src,/hello_1.mp3$/);reminder.advance(5);assert.match(reminderAudio.src,/hello_2.mp3$/);reminder.advance(5);assert.match(reminderAudio.src,/hello_3.mp3$/);reminder.t.answerAttention(false);assert.equal(reminder.sandbox.document.body.classList.values['attention-pulse'],false);reminder.advance(5);assert.match(reminderAudio.src,/no.mp3$/);console.log('PASS: pulse after 3 seconds, rotating greetings every 5 seconds afterward, cancellation on response');

stored={tutorial:true};const cards=boot();cards.t.handleClick({target:{closest:()=>({dataset:{action:'start'}})}});const submitCard=()=>cards.el('plan-form').onsubmit({preventDefault(){}});submitCard();assert.match(cards.el('plan-error').textContent,/Describe/);cards.el('plan-done').value='Finished page';submitCard();assert.equal(cards.el('plan-card-0').hidden,true);assert.equal(cards.el('plan-card-1').hidden,false);cards.el('plan-back').onclick();assert.equal(cards.el('plan-done').value,'Finished page');assert.equal(cards.el('plan-card-0').hidden,false);assert.equal(cards.t.state().running,false);console.log('PASS: one planning card at a time, validation, back navigation and retained input');

stored={tutorial:true};const coach=boot();coach.t.handleClick({target:{closest:()=>({dataset:{colorbot:'coach'}})}});assert.equal(boot().t.prefs.colorRobot,'coach');assert.match(coach.t.robotHTML(),/alt="Coach"/);assert.doesNotMatch(coach.t.robotHTML(),/colorful-robot/);assert.match(coach.t.robotImage({}),/coach\/idle\//);coach.advance(10);assert.match(coach.t.robotImage({}),/coach\/idle-2\/1.webp$/);coach.advance(.3);assert.match(coach.t.robotImage({}),/coach\/idle-2\/3.webp$/);assert.match(coach.t.robotHTML('celebration-buddy'),/coach\/cheer\//);assert.match(coach.t.robotHTML('celebration-buddy'),/data-coach-celebration="true"/);coach.t.prefs.motion=true;assert.match(coach.t.robotImage({},true),/cheer\/1.webp$/);assert.match(coach.t.robotImage({}),/\/1.webp$/);console.log('PASS: Coach selection persists, alternating idle sheets, celebration cheers, and reduced motion');
