const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
let now=100000,interval;const elems=new Map();function el(id){if(!elems.has(id))elems.set(id,{id,value:'',textContent:'',innerHTML:'',hidden:false,open:false,checked:false,classList:{toggle(){}},attributes:{},setAttribute(k,v){this.attributes[k]=v},addEventListener(){},showModal(){this.open=true},close(){this.open=false},querySelector(){return el('query')}});return elems.get(id)}el('mission').value='Read';
let saved={tutorial:true};const localStorage={getItem:()=>JSON.stringify(saved),setItem:(k,v)=>saved=JSON.parse(v)};
const theme={};const document={documentElement:{style:{setProperty(k,v){theme[k]=v}}},getElementById:el,body:{classList:{toggle(){}}},addEventListener(){},querySelector(){return {textContent:''}}};
document.baseURI="https://focus.getadhd.care/";const sandbox={URL,document,localStorage,console,Date:{now:()=>now},setInterval:f=>interval=f,setTimeout:()=>1,clearTimeout(){},window:{addEventListener(){}},Math,JSON};
let code=('<script>'+fs.readFileSync(require('path').join(__dirname,'../timer.js'),'utf8')+'</script>').match(/<script>([\s\S]*?)<\/script>/)[1];code=code.replace('})();','globalThis.test={get:()=>state,prefs,start,pause,run,reset,beginBreak,tour,endTour,practice:()=>practice,handleClick,render,applyTheme,ambient,stopSound};})();');vm.createContext(sandbox);vm.runInContext(code,sandbox);const t=sandbox.test;
function click(action){t.handleClick({target:{closest:()=>({dataset:{action}})}})}function advance(s){now+=s*1000;interval()}
t.start();assert.equal(t.get().running,true);assert.equal(el('ring-fill').attributes['stroke-dashoffset'],'100');assert.equal(el('ready-controls').hidden,true);advance(150);assert.equal(el('ring-fill').attributes['stroke-dashoffset'],'75');assert.equal(el('progress').attributes['aria-valuenow'],'25');t.reset();assert.equal(el('ready-controls').hidden,false);t.start();advance(20);assert.equal(t.get().left,580);t.pause();const left=t.get().left;advance(100);assert.equal(t.get().left,left);t.run();advance(5);assert.equal(t.get().left,left-5);
t.reset();t.run();assert.equal(t.get().running,false);t.start();advance(600);assert.equal(t.get().phase,'checkin');assert.equal(el('ring-fill').attributes['stroke-dashoffset'],'0');assert.equal(t.prefs.stickers,1);advance(600);assert.equal(t.prefs.stickers,1);
t.beginBreak();advance(180);assert.equal(t.get().phase,'next');assert.equal(t.get().running,false);click('next');advance(600);assert.equal(t.prefs.stickers,2);t.beginBreak();assert.equal(t.get().left,300);advance(300);assert.equal(t.get().phase,'finished');assert.equal(t.get().running,false);
t.reset();assert.equal(t.prefs.stickers,2);t.start();t.pause();t.reset();advance(3000);assert.equal(t.get().phase,'ready');assert.equal(t.get().running,false);
t.start();t.tour();assert.equal(t.get().running,false);click('tour-next');click('tour-next');click('practice');advance(10);assert.equal(t.practice().left,0);assert.equal(t.prefs.stickers,2);t.endTour();assert.equal(t.get().running,false);assert.equal(saved.tutorial,true);
console.log('PASS: start, pause/resume, reset/restart, elapsed-time catch-up, one reward per round, short/final breaks, manual next round, quest completion, retained stickers, canceled session safety, isolated tutorial, saved preferences.');

t.reset();t.start();advance(300);assert.equal(t.get().attention,true);assert.equal(t.get().running,false);assert.equal(el('attention').open,true);assert.equal(el('attention-mission').textContent,'Read');const frozen=t.get().left;advance(80);assert.equal(t.get().left,frozen);click('attention-no');assert.equal(t.get().attention,false);assert.equal(t.get().running,false);assert.equal(t.prefs.stickers,2);t.run();advance(1);assert.equal(t.get().attention,false);assert.equal(t.get().running,true);t.reset();t.start();advance(300);click('attention-yes');assert.equal(t.get().running,true);t.reset();assert.equal(el('attention').open,false);advance(600);assert.equal(t.get().running,false);t.prefs.checkins=false;t.start();advance(300);assert.equal(t.get().attention,false);assert.equal(t.get().running,true);t.prefs.buddy=1;t.render();assert.equal(theme['--accent'],'#ff2e88');t.prefs.buddy=2;t.render();assert.equal(theme['--accent'],'#b400ff');console.log('PASS: halfway mission check, paused countdown, Yes resumes, No stays paused, no lost rewards, no duplicate/stale checks, disabled checks, buddy theme colors.');
